config/routes.rb
TaskForce::Application.routes.draw do
  get "acecube/call"

  get "task_force/home"

  get "task_force/activities"

  get "task_force/membership"

  get "task_force/links"

  match '/activities',   :to => 'task_force#activities'
  match '/membership', :to => 'task_force#membership'
  match '/links', :to => 'task_force#links'
  match '/call', :to => 'acecube#call'
  

  root :to => "task_force#home"

end

app/controllers/acecube_controller.rb
class AcecubeController < ApplicationController
  def call
    @title = 'Special Sessions'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/task_force_controller.rb
class TaskForceController < ApplicationController
  def home
    @title = "Home"
  end

  def activities
    @title = "Activities"
  end

  def membership
    @title = "Membership"
  end

  def links
    @title = "External Links"
  end

end

app/helpers/acecube_helper.rb
module AcecubeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_force_helper.rb
module TaskForceHelper
end

app/views/acecube/call.html.erb
<h1><a href="http://www.ieee-wcci2012.org/ieee-wcci2012/index.php?option=com_content&amp;view=frontpage&amp;Itemid=54">
  IEEE World Congress on Evolutionary Computation 2012</a></h1>

<h1>Special Session on Applications of Evolutionary
 Computation in Biomedical Engineering</h1>

<p>
  Biomedical Engineering aims to apply engineering principles to biomedical
  systems. A biomedical system may be very broadly defined as any engineered
  device or apparatus that interacts with a biological entity to achieve a
  medical purpose. This is a fast-growing research area which is throwing up
  many complex problems as researchers grapple with the need to model complex
  systems and interpret massive biomedical datasets.
</p>

<p>
  In this session, we invite contributions from researchers who have applied
  techniques in evolutionary computation to real-world problems in biomedical engineering.
</p>
<h1>Techniques</h1>
<p>
  Techniques may come from the whole range of evolutionary computing,
  including (but not limited to):
</p>

<ul>
  <li>Genetic Algorithms</li>
  <li>Evolution Strategies</li>
  <li>Particle Swarm Optimisation</li>
  <li>Differential Evolution</li>
  <li>Ant Colony Optimisation</li>
  <li>Estimation of Distribution Algorithms</li>
  <li>Hybrids with other approaches</li>
</ul>

<h1>Application Areas</h1>
<p>
  Application areas include but are not limited to:
</p>

<ul>
  <li>Medical diagnostic systems</li>
  <li>Theranostics</li>
  <li>Medical imaging</li>
  <li>Advanced prosthetics</li>
  <li>Biosensors</li>
  <li>Telemedicine</li>
  <li>Treatment or medical equipment design and optimisation</li>
</ul>

<h1>Special Session Organisers</h1>
<p>
  <a href="mailto:j.mccall@rgu.ac.uk">John McCall</a><br>
  IDEAS Research Institute, Robert Gordon University, St. Andrew St.,
  Aberdeen AB25 1HG, Scotland. Phone: +44 (0)1224 262780; Fax: +44 (0)1224 262727.
  (<a href="http://www.comp.rgu.ac.uk/staff/jm">Web Page</a>)
</p>

<p>
  <a href="mailto:h.tang@surrey.ac.uk">Lilian Tang</a><br>
  Department of Computing,University of Surrey, Guildford GU2 7XH, UK.
  Phone: +44 (0)1483 686054; Fax: +44 (0)1483 686051. (<a
  href="http://www.surrey.ac.uk/computing/people/hongying_tang/">Web Page</a>)
</p>

<h1>Programme Committee</h1>
<ul>
  <li>David Cairns, University of Stirling, UK</li>
  <li>George Coghill, University of Aberdeen, UK</li>
  <li>Jose Lozano, University of the Basque Country, Spain</li>
  <li>George Saleh, Moorfields Eye Hospital, UK</li>
  <li>John McCall, Robert Gordon University, UK</li>
  <li>Andrei Petrovski, Robert Gordon University, UK</li>
  <li>Gerald Shaefer, University of Loughborough, UK</li>
  <li>Stephen Smith, University of York, UK</li>
  <li>Lilian Tang, University of Surrey, UK</li>
  <li>Allan Tucker, Brunel University, UK</li>
  <li>Minaya Villasana, Universidad Simon Bolivar, Venezuela</li>
  <li>Wing-Kuen Ling, University of Lincoln, UK</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IEEE Task Force on Biomedical Engineering Applications | <%= @title %></title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
      <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="container">
      <header>
        <h1>
          IEEE Task Force on Biomedical Engineering Applications
        </h1>

        <nav class="round">
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Activities", activities_path %></li>
            <li><%= link_to "Membership", membership_path %></li>
            <li><%= link_to "Special Sessions", call_path %></li>
            <li><%= link_to "External Links", links_path %></li>
          </ul>
        </nav>

      </header>

      <section>

        <%= yield %>

      </section>

    </div>

  </body>
</html>

app/views/task_force/activities.html.erb
<h1>Planned Future Activities</h1>
<p>
  The Task Force will achieve its aims through a range of activities including:
<ul>
  <li>
    biomedical engineering special sessions and tutorials at major computational
    intelligence conferences;
  </li>
  <li>
    multidisciplinary and industry-facing workshops focussed round specific
    applications where critical mass of research can be brought to bear;</li>
  <li>
    journal special issues; and
  </li>
  <li>
    coordinated effort on developing standards for the application of CI to
    important problems in biomedical engineering including benchmarking, data
    interchange formats, data management and ethics, experimental design and validity standards.
  </li>
</ul>


</p>

app/views/task_force/home.html.erb
<h1>Mission</h1>
<p>
  The mission of the Task Force on Biomedical Engineering Applications
  is to promote the research, development, education and understanding
  of the applications of computational intelligence to biomedical engineering.
</p>

<h1>Background and Motivation</h1>
<p>
  Biomedical Engineering (BE) aims to apply engineering principles to biomedical 
  systems. A biomedical system may be very broadly defined as any engineered 
  device or apparatus that interacts with a biological entity to achieve a medical 
  purpose. Examples of biomedical systems include medical diagnostic systems, 
  theranostics, medical imaging, advanced prosthetics, biosensors, telemedicine 
  and many more. This is a fast-growing research area which is throwing up many 
  complex problems as researchers grapple with the need to model complex systems 
  and interpret massive biological and medical datasets. Computational Intelligence 
  (CI) has proven highly successful in its application to more traditional 
  engineering disciplines. CI approaches contribute in a wide variety of ways 
  including design, mathematical, probabilistic and statistical modelling, control, 
  automation and optimisation, safety and reliability, system identification, 
  monitoring and fault detection. There is therefore strong motivation to bring 
  this experience to bear on the considerably more complex research challenges posed by BE.
</p>

<h1>Scope</h1>
<p>
  The scope of the task force will be to identify, support and encourage all
  areas where CI can have a major impact.  Currently applications of CI to BE
  are varied and disparate. They include data mining, probabilistic modelling,
  pattern recognition, classification, optimisation, and parameter estimation
  applied to a wide range of medical conditions. A central focus for the task
  force will be to discover common approaches and problems, clearly identify the
  strengths CI brings and create communities and standards focussed on major
  application areas with potential for real impact and improvement of BE. This
  will bring together existing researchers and also encourage other CI researchers
  into the area.
</p>

<h1>Chair: Professor John McCall</h1>
<p>
  John McCall obtained his PhD in Mathematics at the University of Aberdeen.
  His research for the past 18 years has focussed on the study and analysis of
  a range of naturally-inspired metaheuristics (EA, EDA, PSO, ACO, ANN etc..)
  and their application to learning and optimisation problems. Major themes of
  his research include medical treatment optimisation, particularly cancer-related,
  the development and analysis of novel metaheuristics, particularly Markov-network
  EDAs, and probabilistic modelling for optimisation and learning. Application
  areas of this research include medical decision support, oil and gas operations,
  analysis of biological sequences, scheduling, image analysis and bio-control.
  Prof. McCall is currently Digital Technologies Theme Leader at the IDEAS Research
  Institute of Robert Gordon University, Aberdeen.
</p>

<h1>Vice Chair: Dr Lilian Tang</h1>
<p>
  Lilian Tang received B.Eng. and M.Eng. degrees from Northeastern University,
  P.R. China, and a Ph.D. degree in Medical Informatics from the University of
  Cambridge, UK. She has 15 years of experience in applying machine vision to
  image and video analysis, with a particular focus on the medical domain.
  During this time she has worked with Addenbrookes Hospital, the Royal Surrey
  Hospital, the Royal Botanic Gardens, Kew and Moorfields Eye Hospital on a wide
  range of projects. She is currently a lecturer at the University of Surrey.
</p>

app/views/task_force/links.html.erb
<h1>External Links</h1>
<p>
  <%= link_to("Intelligent Systems Applications Technical Committee (ISATC)", "http://www.ieee-cis.org/technical/isatc/", {:target => "outside_link"}) %>
</p>

<p>
  <%= link_to("IEEE Computational Intelligence Society", "http://www.ieee-cis.org/", {:target => "outside_link"}) %>
</p>

<p>
  <%= link_to("International Medical Informatics Association", "http://www.imia-medinfo.org/new2/", {:target => "outside_link"}) %>
</p>

app/views/task_force/membership.html.erb
<h1>Task Force Membership</h1>
<p>
  <strong>Chair: Prof. John McCall</strong><br />
  IDEAS Research Centre<br />
  Robert Gordon University<br />
  Aberdeen AB25 1HG<br />
  Scotland<br />
  E-mail: <%= mail_to "j.mccall@rgu.ac.uk" %> <br />
  Tel: +44 1224 262780<br />
  Fax: +44 1224 262727<br />
  Web: <%= link_to("http://www.comp.rgu.ac.uk/staff/jm/", "http://www.comp.rgu.ac.uk/staff/jm/", {:target => "outside_link"}) %><br />
</p>

<p>
  <strong>Vice Chair: Dr. Lilian Tang</strong><br />
  Department of Computing<br />
  University of Surrey, UK<br />
  E-mail: <%= mail_to "h.tang@surrey.ac.uk" %><br />
  Tel: 01483 68 6054<br />
  Web: <%= link_to("http://www.surrey.ac.uk/computing/people/hongying_tang/", "http://www.surrey.ac.uk/computing/people/hongying_tang/", {:target => "outside_link"}) %><br />
</p>

<p>
  Prof Rezaul K Begg, PhD SMIEEE<br />
  Biomechanics Unit, SES/ISEAL<br />
  Victoria University - City Flinders Campus PO Box 14428, Melbourne, Vic 8001, Australia<br />
  E-mail: <%= mail_to "rezaul.begg@vu.edu.au" %><br />
  Tel: +61 3 9919 1116 F: +61 3 9919 1242<br />
  Web: <%= link_to("http://www.staff.vu.edu.au/begg", "http://www.staff.vu.edu.au/begg", {:target => "outside_link"}) %><br />
  CRICOS Provider No.00124K<br />
</p>

<p>
  Prof. Riccardo Bellazzi<br />
  Dipartimento di Informatica e Sistemistica<br />
  Università degli Studi di Pavia<br />
  Via Ferrata 1 27100 Pavia (Italy)<br />
  E-mail: <%= mail_to "riccardo.bellazzi@unipv.it" %><br />
  Tel: +39-0382-985720<br />
  Fax: +39-0382-525638<br />
</p>

<p>
  Dr. John Boyle<br />
  Institute for Systems Biology<br />
  1441 North 34th Street<br />
  Seattle, WA 98103-8904<br />
  E-mail: <%= mail_to "jboyle@systemsbiology.org" %><br />
  Tel: (206) 732-1200<br />
  Fax: (206) 732-1299<br />
</p>

<p>
  George Coghill<br />
  Reader, University of Aberdeen<br />
  Room: 231<br />
  E-mail: <%= mail_to "g.coghill@abdn.ac.uk" %><br />
  Tel: +44 (0)1224 273829<br />
  Fax: +44 (0)1224 273422<br />
  Web: <%= link_to("http://www.csd.abdn.ac.uk/~gcoghill/", "http://www.csd.abdn.ac.uk/~gcoghill/", {:target => "outside_link"}) %><br />
</p>

<p>
  Professor David Corne<br />
  School of Mathematical and Computer Sciences<br />
  Heriot-Watt University<br />
  E-mail: <%= mail_to "dwcorne@macs.hw.ac.uk" %><br />
  Tel : +44 (0)131 451 3410<br />
  Fax : +44 (0)131 451 3327<br />
  Web: <%= link_to("http://www.macs.hw.ac.uk/~dwcorne/", "http://www.macs.hw.ac.uk/~dwcorne/", {:target => "outside_link"}) %><br />
</p>

<p>
  Dr. John H. Holmes<br />
  University of Pennsylvania School of Medicine<br />
  E-mail: <%= mail_to "jhholmes@mail.med.upenn.edu" %><br />
  Web: <%= link_to("http://www.cceb.upenn.edu/faculty/?id=172", "http://www.cceb.upenn.edu/faculty/?id=172", {:target => "outside_link"}) %><br />
</p>

<p>
  Professor Jose Lozano<br />
  Intelligent Systems Group<br />
  Department of Computer Science and Artificial Intelligence<br />
  University of the Basque Country<br />
  Manuel de Lardizabal, 1<br />
  20018 Donostia<br />
  Gipuzkoa (Spain)<br />
  E-mail: <%= mail_to "ja.lozano@ehu.es" %><br />
  Tel: +34 943 015 034<br />
  Fax: +34 943 015 590<br />
</p>

<p>
  Dr. Andrei Petrovski<br />
  School of Computing<br />
  Robert Gordon University<br />
  St. Andrew St.<br />
  Aberdeen AB25 1HG<br />
  Scotland<br />
  E-mail: <%= mail_to "a.petrovski@rgu.ac.uk" %><br />
</p>

<p>
  Dr. Stephen Smith - Senior Lecturer<br />
  University of York<br />
  E-mail: <%= mail_to "sls5@ohm.york.ac.uk" %><br />
  Tel: +44 (0)1904 32 2351<br />
  Web: <%= link_to("http://www-users.york.ac.uk/~sls5/", "http://www-users.york.ac.uk/~sls5/", {:target => "outside_link"}) %><br />
</p>

<p>
  Dr. Allan Tucker<br />
  Information Systems and Computing<br />
  St John's 128h<br />
  Brunel University<br />
  Uxbridge<br />
  UB8 3PH<br />
  United Kingdom<br />
  E-mail: <%= mail_to "allan.tucker@brunel.ac.uk" %><br />
  Tel: +44 (0)1895 266933<br />
  Fax: +44 (0)1895 251686<br />
</p>

<p>
  Professor Kevin Warwick<br />
  Cybernetic Intelligence Research Group<br />
  Building: Systems Engineering, Room 171<br />
  University of Reading<br />
  Reading<br />
  Berkshire, UK<br />
  E-mail: <%= mail_to "k.warwick@reading.ac.uk" %><br />
  Tel: +44 (0) 118 378 8210<br />
  Fax: +44 (0) 118 378 8220<br />
  Web: <%= link_to("http://www.kevinwarwick.com/", "http://www.kevinwarwick.com/", {:target => "outside_link"}) %><br />
</p>